### ISSUE TITLE
interfere with with app-switcher-current-workspace-first

### ISSUE THREAD

**Issue by patriziobruno** [Leleat/Tiling-Assistant#126]
**Describe the bug**
Until a few days ago, I could successfully and happily run this extension alongside app-switcher-current-workspace-first. Since last update, this extension has completely prevented app-switcher-current-workspace-first from working. I disabled "App Switcher and Tiling Popup" and disabled and re-enabled both extensions, to no avail. Either I disable Tiling-Assistant or app-switcher-current-workspace-first. I haven't had the opportunity to debug the issue yet, I'll have to disable the tiling assistant because app-switcher-current-workspace-first is more important for my workflow.

**Steps To Reproduce**
- Install Tiling-Assistant 
- https://extensions.gnome.org/extension/1329/app-switcher-current-workspace-first/
- create two or more workspaces
- open 2 or more windows of the same app
- put each window on a separate workspace
- verify that the App Switcher shows at least two icons for the app
- if it doesn't work properly, there should be only one icon

**System Info:**
 - Distro (incl. version): Fedora Silverblue 34
 - GNOME (Shell) version: 40.6
 - Extension version: 31
 - XOrg/Wayland: Wayland

**Journalctl logs**

no error message is printed related to this issue

**List of other extensions**

[app-switcher-current-workspace-first ](https://extensions.gnome.org/extension/1329/app-switcher-current-workspace-first/)
app-switcher_current_workspace_first@fawtytoo
weatherintheclock@JasonLG1979.github.io
appindicatorsupport@rgcjonas.gmail.com
big-avatar@gustavoperedo.org
audio-switcher@albertomosconi
add-username-toppanel@brendaw.com
user-theme@gnome-shell-extensions.gcampax.github.com
background-logo@fedorahosted.org

**Screenshots/-captures**

**Comment by Leleat** [comment]
Fixed with the latest commit. You can [install the extension from main]https://github.com/Leleat/Tiling-Assistant#installation) (you will still get updates from ego), wait for the next ego version, which will come in january, or just manually edit `~/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/altTab.js` with the changes from the last commit (ee80e22).

If you do decide to install Tiling Assistant manually, do the following in that order:

1. reload GNOME Shell (re-login)
2. disable the setting `App Switcher and Tiling Popup` from Tiling Assistant (if you haven't done it before point 1 yet)
3. re-enable app-switcher-current-workspace-first
