### ISSUE TITLE
Drag to Edge tiles to wrong monitor on some multi monitor setups

### ISSUE THREAD

**Issue by jason-bxtn** [Leleat/Tiling-Assistant#137]
**Describe the bug**
When dragging any window to either the left or right edge of the center monitor on a triple monitor setup, the window is tiled on the incorrect monitor.

**Steps To Reproduce**
Please check the attach video, it explains it all. This bug only occurs in Wayland - when the same action is done in either GNOME Classic or GNOME XOrg sessions, things work as expected and the bug cannot be reproduced.

**System Info:**
 - Distro (incl. version): Fedora Workstation 35
 - GNOME (Shell) version: 41.2
 - Extension version: 31
 - XOrg/Wayland: Wayland

**Journalctl logs**
GNOME Shell started at Fri Jan 07 2022 15:05:41 GMT-0500 (Eastern Standard Time)
Registering session with GDM
Received error from D-Bus search provider firefox.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
Timelines with detached actors are not supported
Error in size change accounting.
_The last line is repeated every time a window is dragged to a screen edge and dropped._

**List of other extensions**
I disabled all installed extensions and restarted my computer to make certain no extension conflicts were the cause of this issue. You can see in the video below that this is the case.

**Screenshots/-captures**
Video attached below. Apologies for the length & lackluster quality - I couldn't get any video screen capture software to work, so I recorded the video on my mobile phone.

https://user-images.githubusercontent.com/51170731/148603967-7e08c449-a9a3-41e9-a9d4-21cfc4a73e15.mp4

**Comment by Leleat** [comment]
> Error in size change accounting.
The last line is repeated every time a window is dragged to a screen edge and dropped.

That's unrelated to this. It's about the tiling animations. I just used GNOME's window animations for my tiling as well. That code wasn't written for others to use so you get these warnings but they don't have any actual negative effect. You can disable the animations in `Hidden Settings` and the warnings will disappear.

> Apologies for the length & lackluster quality - I couldn't get any video screen capture software to work, so I recorded the video on my mobile phone.

Don't worry, video was great.

Although I do have trouble thinking of what the problem could be. I grabbed my laptop and hooked it to my main monitor (so I only got a dual monitor setup). Unfortunately, I didn't have any troubles with the multi-monitor aspect on Wayland. Also, based on your video the calculations from my extension itself look correct (after all it does work in Xorg). There are 3 steps you can see:

1. The (blue) tile preview appears correctly when you drag the window to the screen edges
2. Based on the tile preview the grabbed window should tile to previewed position after the grab is released
3. After that, the `Tiling Popup` will appear in the center of the remaining free screen space and offer to tile the remaining windows to fill the remaining free space

The bug seems to happen at step 2. What confuses me is that step 3 is working correctly again. If you drag the window to the left half, the `Tiling Popup` will appear at the center of the right screen half, which means the grabbed window should have been at the left screen half otherwise my calculation of the remaining free screen space would be off and the `Tiling Popup` shouldn't appear on the right screen half...

Kind of a shot in the dark... what happens, if you have 2 windows fully on your middle monitor and instead of tiling via dnd you use the keyboard shortcuts from Tiling Assistant (by default super+numpad; see prefs). Do the windows tile correctly?

**Comment by Leleat** [comment]
Oops, sorry commit referenced wrong issue...

**Comment by jason-bxtn** [comment]
I won't have access to that PC until next week - I'll try the numpad shortcuts then & report what happens.

**Comment by jason-bxtn** [comment]
I happened to have access earlier than planned. Keyboard shortcuts behave exactly as drag-n-drop - the tiled windows & the tiling popup appear on the incorrect monitor.

**Comment by Leleat** [comment]
I've created a [v31-debug branch](https://github.com/Leleat/Tiling-Assistant/tree/v31-debug), which just adds some logs. Can you please install it using [these instructions](https://github.com/Leleat/Tiling-Assistant#installation). Alternatively, you can just apply the changes from the [last commit](https://github.com/Leleat/Tiling-Assistant/commit/25a0ee52ce3a60434581ce1263b5219ff6a17cfa) to `~/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/tilingWindowManager.js`. Reload GNOME Shell (logout and back in again) after the installation/manually applying the changes.

Then please do the following:
1. run `journalctl -fo cat /usr/bin/gnome-shell`
2. tile a window **using the keyboard shortcuts** (since it has the same problem but has simplier code)
3. post the output of the logs between `tile() ------------ /` and `/ ------------ tile()` here
4. also post a screenshot of your display settings from the settings app ¹
5. also tell me which monitor the window, which you tried to tile, was on

¹ This is the part I am interested in

![1](https://user-images.githubusercontent.com/53054301/149420375-5ef0aa72-951c-4f30-a1b0-5403b110367b.png)

**Comment by VandrerenErik** [comment]
I have the very same issue, anyway I can help?

**Comment by Leleat** [comment]
> I have the very same issue, anyway I can help?

Do you have the same setup?

> GNOME (Shell) version: **41.2**
> Extension version: **31**
> XOrg/Wayland: **Wayland**
> **Triple monitors**

and the same problem as in the video from the first comment?

If so, could you try the things I mentioned in the comment just above yours.

**Comment by VandrerenErik** [comment]
Yes, I can try this later today. I leave some extra info and the results of a basic test I ran, hope it is useful.

My monitors are currently like this:
**The monitor in the middle is 1920 by 1200 and the other two are 1920 by 1080 both.**
![image](https://user-images.githubusercontent.com/54407345/150641456-cd0ea884-73e9-4402-8a99-4ea218551fe4.png)
![image](https://user-images.githubusercontent.com/54407345/150641548-692888a7-1c37-4881-910b-a7d10fba9677.png)

After running some basic tests I noted that this only happens if the monitor with a higher vertical resolution is in the middle. Example, if I re-arrange the monitors like seen below the bug will go away. Given this fact, I assume the bug might be related to the different resolutions, the different heights or the alignment of the monitors.

![image](https://user-images.githubusercontent.com/54407345/150641649-67f8ec76-900e-4f0a-bbc4-c8aac2f389e1.png)

**Comment by eliadevito** [comment]
Same problem on dual monitor setup (Notebook connected to external monitor)

This is my layout:

![immagine](https://user-images.githubusercontent.com/5805783/150955952-74ff7476-342b-480d-b170-6820b585a77b.png)

I have noted that if I change the primary display to built-in display the extension seem to works well.

My system:
Fedora 35

**Comment by Leleat** [comment]
> Same problem on dual monitor setup (Notebook connected to external monitor)
>
>  My system:
> Fedora 35
> Gnome 41.3

I tried reproducing this on my laptop connected to 1 exteneral monitor with Fedora 35, GNOME 41.3 and Wayland using the same layout... but I still can't reproduce this 😕

The most helpful thing now would be to get the requested information from one of my [previous comment](https://github.com/Leleat/Tiling-Assistant/issues/137#issuecomment-1012586811):

> I've created a v31-debug branch, which just adds some logs. Can you please install it using these instructions. Alternatively, you can just apply the changes from the last commit to ~/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/tilingWindowManager.js. Reload GNOME Shell (logout and back in again) after the installation/manually applying the changes.
>
>Then please do the following:
>
>    1. run journalctl -fo cat /usr/bin/gnome-shell
>    2. tile a window using the keyboard shortcuts (since it has the same problem but has simplier code)
>    3. post the output of the logs between tile() ------------ / and / ------------ tile() here
>    4. also post a screenshot of your display settings from the settings app
>    5. also tell me which monitor the window, which you tried to tile, was on

**Comment by dolwup** [comment]
Yes, I was on the right monitor and wanted to tile it to the left half of the right monitor but the window got tiled to the right half of the left monitor

**Comment by Cofeiini** [comment]
![settings](https://user-images.githubusercontent.com/7016852/154172399-90b4b1b0-a2c8-47b8-bdfa-903aa4d65dfe.png)
I tried to tile on my Monitor 1 using the hotkeys and later tried to tile on Monitor 3.
```
tile() ------------ /
Current monitor: 1
Window's monitor: 1
Monitor dimensions:
    Monitor 0 x: 1080
    Monitor 0 y: 230
    Monitor 0 width: 2560
    Monitor 0 height: 1440

    Monitor 1 x: 0
    Monitor 1 y: 0
    Monitor 1 width: 1080
    Monitor 1 height: 1920

    Monitor 2 x: 3640
    Monitor 2 y: 446
    Monitor 2 width: 1920
    Monitor 2 height: 1080

Trying to tile: discord
Window.get_work_area_current_monitor.x : 0
Window.get_work_area_current_monitor.y : 0
Window.get_work_area_current_monitor.width : 1080
Window.get_work_area_current_monitor.height : 1920
Window's new x: 0
Window's new y: 960
Window's new width: 540
Window's new height: 960
/ ------------ tile()
```
It seems the orientation is not taken into account in my case, but I can confirm that under certain conditions the tiling breaks.

I've managed to create more logs by trying to tile left twice on my main monitor. This behavior doesn't happen when tiling up or tiling on Monitor 2.
```
tile() ------------ /
Current monitor: 1
Window's monitor: 0
Monitor dimensions:
    Monitor 0 x: 1080
    Monitor 0 y: 230
    Monitor 0 width: 2560
    Monitor 0 height: 1440

    Monitor 1 x: 0
    Monitor 1 y: 0
    Monitor 1 width: 1080
    Monitor 1 height: 1920

    Monitor 2 x: 3640
    Monitor 2 y: 446
    Monitor 2 width: 1920
    Monitor 2 height: 1080

Trying to tile: discord
Window.get_work_area_current_monitor.x : 1080
Window.get_work_area_current_monitor.y : 256
Window.get_work_area_current_monitor.width : 2560
Window.get_work_area_current_monitor.height : 1414
Window's new x: 1080
Window's new y: 256
Window's new width: 1280
Window's new height: 1414
/ ------------ tile()
```

This comes after trying to tile left for the second time on Monitor 3.
```
tile() ------------ /
Current monitor: 2
Window's monitor: 2
Monitor dimensions:
    Monitor 0 x: 1080
    Monitor 0 y: 230
    Monitor 0 width: 2560
    Monitor 0 height: 1440

    Monitor 1 x: 0
    Monitor 1 y: 0
    Monitor 1 width: 1080
    Monitor 1 height: 1920

    Monitor 2 x: 3640
    Monitor 2 y: 446
    Monitor 2 width: 1920
    Monitor 2 height: 1080

Trying to tile: discord
Window.get_work_area_current_monitor.x : 3640
Window.get_work_area_current_monitor.y : 446
Window.get_work_area_current_monitor.width : 1920
Window.get_work_area_current_monitor.height : 1080
Window's new x: 3640
Window's new y: 446
Window's new width: 1920
Window's new height: 1080
/ ------------ tile()
```
There are also logs about "Error in size change accounting".
Hope this helps.

**Comment by Leleat** [comment]
> There are also logs about "Error in size change accounting".

That's unrelated (and doesn't cause an actual problem). I guess it's more of a warning.

>  Hope this helps.

I think it does. But currently I don't have much time to look at this since it's my exam period right now. I'll try to search for a solution during my semester break (which starts next week).

**Comment by federicort** [comment]
Same problem here, as shown in the video.

![image](https://user-images.githubusercontent.com/46429970/158455439-8196e8ed-9282-4cab-82a5-928b3e7198ab.png)


![image](https://user-images.githubusercontent.com/46429970/158455572-a3d8708b-911a-4a58-bbe8-364c199dc035.png)

**Comment by Leleat** [comment]
> I ran the v31-debug branch and I wasn't able to reproduce the problem anymore (and had a new different problem with tiling gnome-terminal) so I checked what you changed and reverted the changes in line 208 and 210. I was able to reproduce the issue after that (the issue I had with gnome-terminal was also solved by this)

Since my workaround in that branch was confirmed to work I've added it to `main` now. I've also added a workaround for the GNOME Terminal issue (which hopefully works reliably).

**Comment by Bananaman** [comment]
@Leleat Just stumbling over from reading Reddit to let you know that your fix worked for another user who had multi monitor issues:

https://www.reddit.com/r/gnome/comments/v6ixsh/comment/ibg38lq/?utm_source=reddit&utm_medium=web2x&context=3

Thanks for Tiling Assistant. It's an absolutely awesome tiler and is my favorite of all, regardless of OS or DE. :heart:
