### ISSUE TITLE
Yet another gnome-terminal bug

### ISSUE THREAD

**Issue by sej7278** [Leleat/Tiling-Assistant#145]
Really starting to think I need to ditch gnome-terminal!

I found that when using your extension, the first time I do ctrl-shift-t to open another tab in gnome-terminal, its moves the whole window to the secondary monitor.

https://user-images.githubusercontent.com/817564/155814900-0faa8a8e-77a0-4f79-ac39-e30c6f071379.mp4

Debian Sid, gnome 41.2, 41.3 and 42-beta

**Comment by sej7278** [comment]
closing as no response, assuming the extension is dead. gnome-console doesn't have this problem btw.

**Comment by Leleat** [comment]
Opps, been busy the last few months.... so I just forgot to respond to this. That being said, I don't think there is much I can do here from an extension since it looks like it was triggered by gnome terminal and doesn't have anything to do with gnome shell. So closing this seems appropriate.

>  42-beta

Fyi, I do plan to add support for 42 in the coming weeks.

**Comment by sej7278** [comment]
42 support would be great thx! I'm already panicking about my workflow lol, gone back to super+cursors for now but that's so basic.

I really only opened this to see if you had any ideas how to work around what definitely seems like a gnome-terminal bug but gnome-console doesn't have the same problem so that's a good enough workaround for me.
