### ISSUE TITLE
Tile to bottom when window is not maximised and Dynamic Keybinding Behaviour -> Tiling State is enabled

### ISSUE THREAD

**Issue by Silejonu** [Leleat/Tiling-Assistant#151]
When Dynamic Keybinding Behaviour -> Tiling State is enabled, pressing the Window restore size shortcut (Super+Down by default) should tile the window to the bottom, similarly to how it works to tile windows to the top.

This is especially useful when using a keyboard without a numpad.

**Comment by Leleat** [comment]
Don't know about this... why can't you just change the `Tile to bottom` short to `Super`+`Down`.

**Comment by Silejonu** [comment]
> Don't know about this... why can't you just change the `Tile to bottom` short to `Super`+`Down`.

I can, but it would be better if it was consistent with how `Super`+`Up` works: 1 tap to maximise the window, 2 taps to tile to top.

So, in the case of `Super`+`Down`, it would be: 1 tap to minimise the window, 2 taps to tile to bottom.

**Comment by Leleat** [comment]
> Super+Down, it would be: 1 tap to minimise the window, 2 taps to tile to bottom.

That doesn't work. After you minimize a window, a new window gets focus and all shortcuts will be acting with that window. So you'll never be able to reach *"2 taps to tile to bottom"*. If you want to swap the 1 and 2, you have the same exact behaviour as the `Tile to bottom` shortcut. Additionally, you could never restore a window's size with just 1 shortcut anymore (which is the point of `Restore Window Size`).

The reason why the shortcut is `Super` + `Down` is because I want Tiling Assistant to integrate as seamlessly as possible with vanilla GNOME (or at least Fedora). With the default settings of my extension I *only* want to add quarter tiling and the Tiling Popup. So if a user deviates from the defaults and enables a `Dynamic Keybinding Behaviour`, I also expect them to change the keyboard shortcuts, if they want a mirroring behaviour of `Super`+`Up`/`Down`.

With that said sorry, but I am not going to implement this.

**Comment by Silejonu** [comment]
Sorry, I meant "unmaximise", not "minimise".
