### ISSUE TITLE
Super + Arrow Keys shortcut does not work

### ISSUE THREAD

**Issue by carlocastoldi** [Leleat/Tiling-Assistant#167]
**Describe the bug**
I would like bind `SuperKey`+`ArrowUp`+`ArrowRight` to tile at the top-right quarter (and other quarters+arrows combinations) because I find it an intuitive shortcut + I have a TKL keyboard without numpad.
If I try to do so in the Shortcut tab, it results in no apparent input being taken, but it switches focus in the extensions settings to some other element of the GUI.

**System Info:**
 - Distro: Manjaro
 - GNOME (Shell) version: 42.1
 - Extension version and from where : `gnome-shell-extension-tiling-assistant-git` from AUR: commit [ee9ffa1](https://github.com/Leleat/Tiling-Assistant/commit/ee9ffa1f3bfa257cd453d9986b159c930ef12f65)
 - Wayland

**Comment by Leleat** [comment]
> SuperKey+ArrowUp+ArrowRight

That's not a valid keyboard shortcut. A shortcut consists of modifiers (keys, which by themselves don't do anything; for instance `Ctrl` or `Shift` ) and 1 'normal' key. Having multiple normal keys as part one shortcut isn't a thing. This isn't limited to my extension. That's pretty universal. Otherwise there would be conflicting shortcuts. For example, `Super` + `Up` or `Super` + `Right` would activate before `Super` + `Up` + `Right` because a user can't simultaneously press `Up` and `Right`. `Up` is always pressed before `Right` (or `Right`before `Up`)...

You can however use the `Dynamic Keybinding` setting `Tiling State` under the `General` tab.  With that setting the keyboard shortcuts to tile to the top (/maximize), left, right, and bottom will change their behaviour based on the focused window's tiling state. For example, when you activate the shortcut `Tile to bottom` while the window is tiled to the right half, the window will tile to the bottom-right instead of tiling to the bottom half. So it's pretty similiar to what you want.

**Comment by carlocastoldi** [comment]
Oh thanks for the clarification. That makes some sense.
`Dynamic Keybinding` seems to be the way to go, but I am afraid they don't work on my system:

https://user-images.githubusercontent.com/34198340/166224821-fe7535ea-0e86-4df2-b02a-3b516a454fa5.mp4

**Comment by Leleat** [comment]
>  Dynamic Keybinding seems to be the way to go, but I am afraid they don't work on my system:

Ah that's a bug and I know what's going on. I'll fix it later today

**Comment by Leleat** [comment]
Fixed it now in `main`.

**Comment by carlocastoldi** [comment]
that fixed it! Thanks for the fast intervention ^^
