### ISSUE TITLE
Wrong tiling when window is quickly moved between monitors

### ISSUE THREAD

**Issue by LukasPietzschmann** [Leleat/Tiling-Assistant#189]
**Describe the bug**
When a window is quickly moved from one screen to another, it gets tiled to the monitor it was moved from and not to the monitor it was moved to.
Here's a recording of the behavior:
[Screencast from 15.07.2022 09:51:35.webm](https://user-images.githubusercontent.com/49213919/179179769-bd4620fb-7983-4c50-b852-93e906d1ef17.webm)

**Steps To Reproduce**
1. Open a window on one of multiple monitors
2. Quickly drag the window to an edge of another window

**System Info:**
 - Distro (incl. version): Fedora 36
 - GNOME (Shell) version: GNOME: 	42.2; GNOME-Shell: 42.3.1
 - Extension version and from where (e. g. EGO, `main` branch...): v34 from extensions.gnome.org
 - XOrg/Wayland: Wayland

**Journalctl logs**
There was no relevant output.

**Idea for a fix**
Maybe it would be sufficient to introduce a longer delay before a window gets tiled to fix this behavior.

**Comment by Leleat** [comment]
> When a window is quickly moved from one screen to another, it gets tiled to the monitor it was moved from and not to the monitor it was moved to.

This is actually a [feature](https://github.com/Leleat/Tiling-Assistant/issues/46) 😅. There's is a 'grace period' of 150 ms, in which the window will snap to the old monitor, when you move the window to a new monitor. This way you don't need to slowly creep towards an edge of a monitor to tile windows, just because there happens to be another monitor bordering that edge. 150 ms is also fairly short, so it's easy to consciously move a window to a new monitor without accidently triggering tiling... if you know that this feature exists. 

Are you a new-ish user of Tiling Assistant and quickly noticed this feature? Then I guess it's worth making this opt-out since there are probably other users with similiar behaviour of moving windows quickly across monitors. Or did you just randomly come across this feature?

**Comment by LukasPietzschmann** [comment]
Thanks for your fast reply :)
> Are you a new-ish user of Tiling Assistant and quickly noticed this feature?

Yes, I am a pretty new user of Tiling Assistant and I actually was expecting to find an option to disable this delay, as I first encountered this feature. But as there was none, I figured it might be a bug ':)
>Then I guess it's worth making this opt-out

Maybe being able to adjust the delay would be even better than a on/off toggle?

**Comment by Leleat** [comment]
I've added a toggle to disable the grace period to the advanced settings.

**Comment by LukasPietzschmann** [comment]
Thanks a lot for adding the option. It works great. Now I can fling my mouse around like a madman again :)
