### ISSUE TITLE
Disable Rounded Corner

### ISSUE THREAD

**Issue by rasyidrafi** [Leleat/Tiling-Assistant#192]
**Describe the bug**
Before i am installing this extension, i has no issue when tiling a window to the left or right (default ubuntu)

This extension help a lot,
but i have issue whenever im tiling a window,
the rounded window doesnt fill up correcly

See Below Screenshoot

Before Install
![image](https://user-images.githubusercontent.com/69502214/179886904-6b44f2fd-e08f-4850-9296-3b73480aee4a.png)
![image](https://user-images.githubusercontent.com/69502214/179886926-be3f6e03-c023-486f-86af-21c1f7b94148.png)

After Installing:
![image](https://user-images.githubusercontent.com/69502214/179886526-1e6997ce-1beb-467b-9900-93116131f510.png)

![image](https://user-images.githubusercontent.com/69502214/179886598-8e48f668-7f70-46cf-b2d5-ad162acb837f.png)

![image](https://user-images.githubusercontent.com/69502214/179886649-0ce4404e-9ea0-480c-8052-f7042a8c6503.png)

**Steps To Reproduce**
Tile a window before installing extension,
and Do it again after installing

**System Info:**
 - Distro : Ubuntu 22.04 LTS x86_64
 - GNOME (Shell) version: GNOME 42.2
 - Extension version and from where (e. g. EGO, `main` branch...): Main
 - XOrg/Wayland: Wayland

**Comment by Leleat** [comment]
Unfortunately, this is unfixable because of the limitations of being a **GNOME Shell** extension. All tiling extensions just move and resize windows like a user would... just programmatically. So technically it's just fake-tiling and all windows are still 'floating'. Only a proper implementation in GNOME would be able to remove the rounded corners...
