### ISSUE TITLE
Feature request: Keybinding modifier to trigger Tilling Assistant

### ISSUE THREAD

**Issue by forteller** [Leleat/Tiling-Assistant#212]
Hi! Love the extension, thank you for your work!

My idea for a new feature would be to be able to choose between using the Tiling Assistant (TA) or not by holding Shift (or other modifier).

So how it is now is that when I move a window to the left or right with Super + arrow, the TA always automatically shows up on the other side. That's perfect when you move the window because you want to work with two windows. But often I find myself just moving the window to make it smaller/get shorter text lines on whatever website I'm on. Then the TA is only in the way.

I'd love it if I could set a modifier to either use or not use TA each time I move a window with Super + Arrow. So that either TA only is triggered when using Shift + Super + Arrow, and otherwise it's not triggered – or the other way around.

Thanks! :)

**Comment by Leleat** [comment]
> My idea for a new feature would be to be able to choose between using the Tiling Assistant (TA) or not by holding Shift (or other modifier).
>
> So how it is now is that when I move a window to the left or right with Super + arrow, the TA always automatically shows up on the other side. That's perfect when you move the window because you want to work with two windows. But often I find myself just moving the window to make it smaller/get shorter text lines on whatever website I'm on. Then the TA is only in the way.

There used to be a  keyboard shortcut to toggle the `Tiling Popup` to address this exact scenario. In practice it was kinda clunky since you may forget that you disabled the `Tiling Popup` and end up confused when it doesn't popup...

I do like the idea of temporarily ignoring/skipping the next `Tiling Popup`.

I will implement your modifier suggestion for tiling windows with the mouse. It will be disabled however as all mods are already bound to a function by default.

But I am got going the modifier way with keyboard shortcuts though since it's too limiting for the user.  E. g. if the user set `Super`+`Left` to tile the window to the left. They may set `Other Mod`+`Super`+`Left` to a different 'directional action' (for instance, moving the window to a different workspace/display, switching workspaces, tiling the window to the top-left etc).

I think I am just gonna add 4 new shortcuts to tile without calling the `Tiling Popup` (or 8? do you also want them for the quarters?). That way you can still achieve this behaviour

> move a window with Super + Arrow. So that either TA only is triggered when using Shift + Super + Arrow, and otherwise it's not triggered – or the other way around.

**Comment by Leleat** [comment]
I've implemented it the way I suggested (i. e. a modifier for the mouse based tiling and extra shortcuts for the keyboard based tiling). I've hidden the settings by default behind the advanced/experimental toggle and they are unbound by default.

Feel free to test them and report any issues you discover.
