### ISSUE TITLE
Error in size change accounting

### ISSUE THREAD

**Issue by francoism90** [Leleat/Tiling-Assistant#213]
**Describe the bug**
Error in size change accounting

**Steps To Reproduce**
* journalctl -xfe
* Slide windows from left to right/right to left

**System Info:**
 - Distro (incl. version): Fedora 37 + Arch Linux
 - GNOME (Shell) version: 43.1
 - Extension version and from where (e. g. EGO, `main` branch...): Gnome Extensions
 - XOrg/Wayland: Wayland

**Journalctl logs**

```bash
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
Timelines with detached actors are not supported. <unnamed>[<Gjs_ui_iconGrid_BaseIcon>:0x55ed61f91440] in animation of duration 200ms but not on stage.
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
```

**Comment by Leleat** [comment]
> Error in size change accounting.

This is caused by my extension misusing GNOME's window animations. You can get rid of this messages by turning of the animations off in the extensions preferences.

I don't intend to do anything about it from my side because that would probably require me to create custom animations. I am not really keen on that since those messages don't actually have any impact on the functionality of the extension and seem to be [just a warning](https://gitlab.gnome.org/GNOME/mutter/-/blob/main/src/compositor/meta-window-actor.c#L774).

If someone really wants to create custom animations, I'll gladly accept a PR.

**Comment by francoism90** [comment]
@Leleat It does fill up the journal, but if this is a Gnome bug, you cannot do anything about this. :)

Thanks for the detailed answer.

**Comment by Leleat** [comment]
@asegarra depending on your installed extension version this may vary slightly:

you need to go to/enable the advanced settings (header bar button in the preference window). Then the animation perference will either be in the advanced settings or appear in the `General` tab in the preference window.

**Comment by asegarra** [comment]
> @asegarra depending on your installed extension version this may vary slightly:
> 
> you need to go to/enable the advanced settings (header bar button in the preference window). Then the animation perference will either be in the advanced settings or appear in the `General` tab in the preference window.

That was it, thanks!
