### ISSUE TITLE
Active Window Hint Roundness

### ISSUE THREAD

**Issue by Aylur** [Leleat/Tiling-Assistant#222]
In ```AlwaysActiveWindowHint``` Class for the style you are using outline which ignores ```border-radius```. I understand the issue why you are using ```outline``` for the outer border, and ```border``` for the inner border.
Instead of using ```outline``` how about this?
````javascript
const wRect = window.get_frame_rect();
this.set({
    x: wRect.x - (outerBorderSize/2),
    y: wRect.y - (outerBorderSize/2),
    width: wRect.width + outerBorderSize
    height: wRect.height + outerBorderSize
});
````
Then using ```border-width``` for the inner border, with this, using ```border-radius``` would be possible.
Only issue with this is if the ```outerBorderSize``` is an odd number the border is  misaligned and the corners look funky. A solution could be rounding it or letting the user know.

**Comment by Leleat** [comment]
IIRC, I thought about rounding the border but ultimately decided against it because windows can have varying degree of 'roundness' and even have a mix of rounded and not rounded corners. So it would end up looking weird...

I guess I can add a (hidden) setting to allow the user to make that choice. Although I don't have much time now since my exams are starting next month and I am also in the process of (slowly) rewriting the current code.

**Comment by EdiDD** [comment]
It is very nice done in **forge** extension. You can check and maybe adapt something similar:
https://github.com/forge-ext/forge

**Comment by Leleat** [comment]
> It is very nice done in **forge** extension. You can check and maybe adapt something similar: https://github.com/forge-ext/forge

Thanks for the hint but I've already opened an MR that addresses this: https://github.com/Leleat/Tiling-Assistant/pull/344.

I only want to make one more release with some bugfixes before merging it. .
