### ISSUE TITLE
Gap with screen border is always 4 pixels

### ISSUE THREAD

**Issue by biscottaro** [Leleat/Tiling-Assistant#224]
As title says, setting any value has no effect. Gap between windows works fine however. I'm on Debian testing, Gnome 43, and version should be the same. Should I check with master?

**Comment by Leleat** [comment]
> Should I check with master?

It wouldn't make a difference. The only commits since the last EGO release were pretty much only translations. That being said, I can't reproduce your issue on Fedora 37 (GNOME Shell 43.2).

Some notes about the screen gaps settings:

- the settings don't apply retroactively. They only apply to windows tiled after the settings were changed.
- there are 2 separate 'screen gap' settings. A uniform `Screen Edges` gap and individual gaps (top, left, bottom and right) . The individual gaps will be shown if you've enabled the advanced/experimental settings (with the button in the header bar). IIRC, the individual gaps will take precedence over the uniform gap. So make sure you've set their value to 0, if you want to use the uniform gap.

To make sure this is a bug, can you confirm that this is not an issue caused by one of those 2 points?

**Comment by biscottaro** [comment]
Thank you, i wasn't aware of the advanced menu. That was indeed the problem, i had set them all up at 4. I set them like that in an earlier version of the extension, where they were still visible, and somehow the configuration carried over
