### ISSUE TITLE
"Gaps" settings no longer do anything

### ISSUE THREAD

**Issue by rshanule** [Leleat/Tiling-Assistant#225]
No matter what values I assign to "Screen Edges" and/or "Windows", it does not change the gaps that actually get applied. Instead, there is always a gap between windows, and a gap on the left and right edges of the screen, with no gap at all on the top or bottom. This bug seems to have appeared around the same time the "Top bottom left right" options were replaced with just one global option (a change I'd rather see reversed anyway, as being able to change each value before was useful for my specific DE setup).

The "Maximized windows" toggle does appear to work however.

**System Info:**
 - Distro (incl. version): Gentoo Linux (~amd64 Testing Branch)
 - GNOME (Shell) version: 43.2
 - Extension version: 39 (from GNOME Shell extensions website)
 - XOrg/Wayland: Happening on both.

**Journalctl logs**
Gentoo does not use journalctl.

**Comment by Leleat** [comment]
> a change I'd rather see reversed anyway, as being able to change each value before was useful for my specific DE setup

I didn't remove the individual gaps. I've only hidden them behind the 'advanced settings' toggle¹ because I didn't think it makes sense for most users to use different settings for the screen gap. That's why I've introduced a general screen gap setting.

If you set gaps for individual screen gaps, they will overwrite the general screen gap setting. I guess that was a pretty bad user experience for existing configs, which didn't have the advanced settings 

¹ you can find the setting in the header bar of the preference window

**Comment by rshanule** [comment]
Ah, found it. Thanks. That is quite the obscure location for an advanced settings menu though.
