### ISSUE TITLE
[Feature Request] set overview size of maximized windows

### ISSUE THREAD

**Issue by Magnotec1** [Leleat/Tiling-Assistant#233]
When having a single window open on a monitor, and the window is maximized, in overview the window takes up the whole overview for that screen. Would be useful to be able to set the size that the window takes up in the overview.

**Comment by Leleat** [comment]
This doesn't seem related to the idea of tiling since the overview with window previews, so I am closing this and don't intend to add it to T-A.

The extension`just-perfection` may support this already. See https://gitlab.gnome.org/jrahmatzadeh/just-perfection/-/issues/10, there is a commit which say it fixes that issue.
