### ISSUE TITLE
a "maximized tile" is not a truly maximized window

### ISSUE THREAD

**Issue by ygypt** [Leleat/Tiling-Assistant#237]
If you slap a window against the top of the screen to maximize it, it is not actually maximized. This is far more evident when you have gaps on with "affect maximized windows" enabled.

The result is that the window will cover the entire screen, yes, but you can still press the maximize button to truly maximize it. This means that if you want to un-maximize a "maximized" window, you gotta press the maximize button twice. (or you could just grab the window which will rip it out of max mode but still)

steps to reproduce:
1. set up gaps and flip the "maximized windows" button
2. slap a window against the top of the screen to make it "maximize"
3. behold: pressing the maximize button makes it actually maximize (like a monocle mode)
4. if you then un-maximize it with the button, its not properly tiled

**Comment by Leleat** [comment]
This is a limitation of being a GNOME Shell extension. See #61 for more. No window is actually ever 'tiled'. All windows are just floating windows, which are moved and resized by the extension. It is impossible to fix because mutter is the proper place to implement tiling (and not GNOME Shell).

As a side note: 'maxmized' windows will use a true maximize, if you've disabled the maximize-with-gaps setting.
