### ISSUE TITLE
tilegroups-in-app-switcher is not discoverable

### ISSUE THREAD

**Issue by Marathon2112** [Leleat/Tiling-Assistant#246]
The `gsettings` key `tilegroups-in-app-switcher` is not discoverable in version 39 of the extension.

Even after activating the advanced settings, there is no way to set the key from the GUI.

**Comment by Leleat** [comment]
I removed the setting because after using it for some time I thought it kinda sucked... I only noticed downsides after extended use; e.g.

- you can no longer just super+tab. You may need to use the arrow keys or the key-above-tab as well
- the app switcher may become unnecessarily long since app icons may be included multiple times
- it's hard to differentiate between different tile groups since there are only app icons

In the end, it looked nice that tile groups are grouped in the app switcher as well. But you use the app switcher to search for and focus *one* window. While multiple windows may be raised as a group, you will still only interact with one window at a time. So it's easier to look for that window in the default app switcher. That's why I decided to hide `tilegroups-in-app-switcher` (and not even include it in the advanced/experimental settings).

I'd like to improve the integration of the tile groups with GNOME Shell in general. For instance showing tile groups together in the overview, dash etc... At that time I may also revisit the app switcher. But those are long-term plans and not happening in the near future. So for now, if you want to use the setting, you need to manually set the gsettings key with `gsettings --schemadir ~/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/schemas set org.gnome.shell.extensions.tiling-assistant tilegroups-in-app-switcher true`.

**Comment by Marathon2112** [comment]
Ah, good to know that the setting was hidden on purpose.

One use case when this becomes particularly useful is when you have, say, multiple text editor windows and multiple PDF viewer windows, and one of each gets tiled for a specific purpose (e.g. latex document generation). Then, having the tile group highlighted in the app switcher makes it easy to switch to it without cycling through all open windows.

However, one could argue that the use of GNOME workspaces would circumvent this issue altogether.

**Comment by janopae** [comment]
@Leleat Is this feature going to be dropped? If yes, this would significantly ease the implementation of #298. If not, I'd try to support this in my implementation.
