### ISSUE TITLE
Jetbrain Rider Freeze when switching Desktop

### ISSUE THREAD

**Issue by LeeRoyManea** [Leleat/Tiling-Assistant#270]
When i do switch between Desktops (Control + Super + Right)  (Control + Super + Left) Jetbrains Rider becomes unresponsive and freezes.  

This only occurs when Tiling Assistant is enabed.

System Info:
 - Distro (incl. version): Fedora 38  
 - GNOME Shell version: 44.2
 - Extension version and from where: 41 from Gnome Extension store
 - XOrg/Wayland: Wayland

**Comment by LeeRoyManea** [comment]
I have the same Issue with the tiling manager "Forge".
So it is maybe more a gnome or jetbrain thing. 
I have noticed that the rider window is flickering after switching the detktop back to the one where the window is displayed.

**Comment by Leleat** [comment]
> I have the same Issue with the tiling manager "Forge".

Then it's likely a bug in GNOME (or jetbrain) since all tiling extensions use the same basic API from GNOME Shell (or rather mutter). It's not the first time something like this was reported (to mutter). Although in the past it was only x11 IIRC. So I am closing this.

If you can, try out other tiling extensions (like gTile, ...) and if you can find a tiling extension that doesn't have this problem, feel free to reopen this.
