### ISSUE TITLE
rework arch PKGBUILD to compile completely from source

### ISSUE THREAD

**Issue by VeldoraTheDragon** [Leleat/Tiling-Assistant#296]
**Briefly describe how the feature should work**
The current `PKGBUILD` fails at stage `build()`,  when building inside an archlinux docker-container (**important:** use docker, not podman), due to the restrictions of the default seccomp profile.
The issue occurs on the line, where `gnome-extensions pack` gets executed.

Thy could add `--security-opt seccomp=unconfined` as a `docker run` parameter, but this would be a major security risk.

I've rewritten the PKGBUILD with the original [build.sh](https://github.com/Leleat/Tiling-Assistant/blob/main/scripts/build.sh) in mind.
See: https://paste.gg/p/anonymous/2a2b7bf574354a359fd50fa041ea71c2

**Explain why this feature should be added**
It should be added, to enable building inside a docker-container for different distros (e.g. alpine, debian) (or to only get the final package, without installing the makedeps, deps on the main system) without having to disable the default seccomp profile, which opens a major security risk. (Container with too many permissions).

See [here](https://docs.docker.com/engine/security/seccomp/) which, restrictions are enabled by default.

I've tested the compilation and installation on an archlinux gnome-system and it works flawlessly. 
The extension works aswell.

**Comment by Leleat** [comment]
Thanks, I am not an arch user so it's been a while since I've last looked up how the AUR works and besides _using_ a few containers I am not very knowledgable about the technical details. That's why I've just copied your `PKGBUILD` since the changes seem fine to me at first glance.

Only thing I've changed is the `source`. It's now

```
source=("${pkgname}::git+https://github.com/Leleat/Tiling-Assistant.git#tag=v${pkgver}")
```

That just fits better in my current workflow/scripts. I imagine that's no issue, right?
