### ISSUE TITLE
gnome-shell crash with failed assertion window->stack_position >= 0 

### ISSUE THREAD

**Issue by harmathy** [Leleat/Tiling-Assistant#329]
**Describe the bug**

When moving a window to another display hitting the top border (initializing maximize) gnome-shell crashed.

**Steps To Reproduce**

I couldn't reproduce the issue

**System Info:**
 - Distro (incl. version): Archlinux
 - GNOME Shell version: 46.0
 - Extension version and from where (e. g. EGO, `main` branch...):  46
 - XOrg/Wayland: Wayland

**Journalctl logs**

```
../glib/gobject/gsignal.c:2685: instance '0x5ae3e92c97d0' has no handler with id '868753'
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
**
libmutter:ERROR:../mutter/src/core/window.c:5380:meta_window_get_workspaces: code should not be reached
Bail out! libmutter:ERROR:../mutter/src/core/window.c:5380:meta_window_get_workspaces: code should not be reached
== Stack trace for context 0x5ae3e0c05d00 ==
#0   5ae3e0cd11b0 i   file:///home/max/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/tilingWindowManager.js:157 (199e0a8b59c0 @ 857)
#1   5ae3e0cd10f0 i   file:///home/max/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/moveHandler.js:264 (199e0a899d30 @ 495)
#2   5ae3e0cd1068 i   file:///home/max/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/moveHandler.js:233 (199e0a899ce0 @ 48)
#3   5ae3e0cd0fd8 i   resource:///org/gnome/shell/ui/init.js:21 (27ff14c70bf0 @ 48)
```

**Comment by sans-c** [comment]
I too did experience similar issues. I do not know how to trigger this reliably. If my observations turn out to be a different issue, I'll create a new one.

For now let me add here that I sometimes have issue with stuck "tiling previews". The blue preview shade would sometimes get stuck until I move the window which I tried to tile. Also I have observed some seemingly related shell crashes.

I will provide more info/post logs when I figure something out. As in my other issue: all this started with gnome 46. Before that, I had no issues to think of.

**Comment by julienfalque** [comment]
I'm facing the same issue with a different scenario:
1. Firefox is tiled on the left side of the screen
2. For some unknown reason Firefox starts to have weird display issues, making it unusable
3. I quit Firefox and restart it, hoping to fix that
4. I try to tile Firefox to the left side of the screen again
5. When the "tiling preview" shows up, the system hangs a few seconds, then GNOME Shell crashes

`journalctl` gives me the same error. I don't know if Firefox display issues and the crash are actually related though.

**Comment by sans-c** [comment]
> I'm facing the same issue with a different scenario:

Maybe you too can try https://github.com/Leleat/Tiling-Assistant/issues/331#issuecomment-2029653612.

I am yet to run into any problems since I am using this. I didn't keep a close eye on the logs since then but I felt I didn't need to. No crashes or weirdness since then. This is anecdotal of course but maybe worth a try.

**Comment by julienfalque** [comment]
I applied the changes. I'll see if the issue happens again.

**Comment by CodeDrivenMitch** [comment]
I seem to have the same issue:
![image](https://github.com/Leleat/Tiling-Assistant/assets/3278878/47e0f700-0087-49b8-8cfb-74207ac2b2e6)

Fresh Ubuntu 24.04 install on a Dell Laptop, Gnome 46

**Comment by Leleat** [comment]
So I've tried taking a look at this and unfortunately I didn't get far... The code flow goes like this

1. Tiling Assistant::MoveHandler._onMoveFinished
2. Tiling Assistant::TilingWindowManager.tile
3. Tiling Assistant::Meta.Window.get_work_area_for_monitor
4. __Mutter__::window.meta_window_get_work_area_for_logical_monitor
5. __Mutter__::window.meta_window_get_workspaces
6. Then we hit the assert [in this line in mutter](https://gitlab.gnome.org/GNOME/mutter/-/blob/46.0/src/core/window.c?ref_type=tags#L5380) **

Apparently, for some reason `window->workspaces == NULL` is true. But I don't see how it's possible for Tiling Assistant to cause that as T-A doesn't operate on such a low level. So ATM, I tend to believe this isn't (directly) caused by T-A. 

A reliabe reproducer would be really helpful for further investigation.

---

** In Mutter's issue tracker there is someone else who hit the same assert [here](https://gitlab.gnome.org/GNOME/mutter/-/issues/3224). But that one appears to be about an unmanaged window, which shouldn't be the case in this issue.

**Comment by julienfalque** [comment]
For the record, I never experienced the issue again since [my previous comment](https://github.com/Leleat/Tiling-Assistant/issues/329#issuecomment-2041459943) (totally forgot to post an update here, sorry 😅)

**Comment by vanvugt** [comment]
Ubuntu bug: https://bugs.launchpad.net/bugs/2068539

**Comment by Leleat** [comment]
I have merged some code that handles the crash when a window unexpectedly crashes during a grab/tiling operation. I am gonna make a new release in a few days on extension.gnome.org. If this crash still occurs with the new release, please report back.

**Comment by sans-c** [comment]
Just some quick feedback: no issues or crashes for me since april. I am always on the latest release as far as I can tell and everything I use just works as expected. I am very happy with this extension. :) Maybe someone else who had issues can chime in and report if the situation improved for them.

**Comment by harmathy** [comment]
I ran this extension for over a month now without any crash. I'd consider this issue fixed.

**Comment by harmathy** [comment]
Thank you, @Leleat !

**Comment by ahati** [comment]
Following up on this — seeing what appears to be the same root cause resurface on **GNOME 50 / mutter 50.1**, though the assertion that fires is different. Asking the maintainers to consider reopening.

## Crash

Dragging a window toward the top edge such that the drop target is a **maximize** (especially across monitors) crashes gnome-shell with **SIGABRT (signal 6)** and drops the session to GDM.

```
gnome-shell: (../clutter/clutter/clutter-actor-meta.c:94):clutter_actor_meta_real_set_actor: runtime check failed: (!priv->actor || !CLUTTER_ACTOR_IN_PAINT (priv->actor))
gnome-shell: clutter_actor_get_stage: assertion 'CLUTTER_IS_ACTOR (actor)' failed
gnome-shell: **
gnome-shell: Clutter:ERROR:../clutter/clutter/clutter-paint-nodes.c:932:clutter_actor_node_new: assertion failed: (actor != NULL)
gnome-shell: Bail out! Clutter:ERROR:../clutter/clutter/clutter-paint-nodes.c:932:clutter_actor_node_new: assertion failed: (actor != NULL)
gnome-shell: GNOME Shell crashed with signal 6
```

## Stack trace

```
#0  resource:///org/gnome/shell/ui/windowManager.js:1281   // actor.paint_to_content(oldFrameRect)  💥
#1  resource:///org/gnome/shell/ui/windowManager.js:1273   // _prepareAnimationInfo(...)
#2  .../src/extension/tilingWindowManager.js:206            // window.maximize()
#3  .../src/extension/moveHandler.js:262                    // Twm.tile(window, this._tileRect, …)
#4  .../src/extension/moveHandler.js:233                    // grab-op-end → _onMoveFinished(window)
#5  resource:///org/gnome/shell/ui/init.js:20
```

## Root cause

Same native-maximize branch in `tile()` that #329 pointed at (`tilingWindowManager.js`, around line 199–209 on `main`):

```js
if (maximize && !Settings.getBoolean('maximize-with-gap')) {
    window.tiledRect = null;
    window.move_to_monitor(monitor);        // :204
    if (window.maximize.length === 0)       // GNOME 49+ dropped the param
        window.maximize();                  // :206  ← fires size-change synchronously
    else
        window.maximize(Meta.MaximizeFlags.BOTH);
    return;
}
```

`window.maximize()` emits a `size-change` synchronously. gnome-shell's `_sizeChangeWindow` → `_prepareAnimationInfo` then calls `actor.paint_to_content(oldFrameRect)` (windowManager.js:1281) to snapshot the window actor for the maximize animation. But the actor was just detached from its stage by `move_to_monitor()` while the move grab is still ending, so it has no valid stage — hence the warnings immediately before the abort:

```
clutter_actor_get_stage: assertion 'CLUTTER_IS_ACTOR (actor)' failed
clutter_actor_node_new: assertion failed: (actor != NULL)   → SIGABRT
```

On Wayland, gnome-shell *is* the compositor, so killing it destroys every surface and ends the session — which is why this reads as a logout/GDM restart rather than a crash.

The reason this is the same bug as #329 despite a different assertion: the trigger, entry point (`moveHandler.js:233` → `tilingWindowManager.js` maximize branch after `move_to_monitor`), and underlying mistake (synchronous `maximize()` right after a monitor swap) are identical — only the assertion mutter/clutter hits differs across versions (`meta_window_get_workspaces` on 46, `clutter_actor_node_new` on 50).

## Suggested fix

Defer `maximize()` to the next idle so the actor re-attaches to a stage before gnome-shell tries to paint a clone of it, and skip the no-op `move_to_monitor`:

```diff
         if (maximize && !Settings.getBoolean('maximize-with-gap')) {
             window.tiledRect = null;
-            window.move_to_monitor(monitor);
-            if (window.maximize.length === 0) // Gnome 49 removed the parameter in maximize()
-                window.maximize();
-            else
-                window.maximize(Meta.MaximizeFlags.BOTH);
+            if (window.get_monitor() !== monitor)
+                window.move_to_monitor(monitor);
+
+            // Defer maximize() to the next idle. Calling it synchronously
+            // right after move_to_monitor() — while the move grab is still
+            // ending — makes gnome-shell's maximize animation snapshot the
+            // window actor before it has re-attached to a stage, which aborts
+            // the compositor:
+            //   clutter_actor_node_new: assertion failed: (actor != NULL)  [signal 6]
+            const maximizeFlags = window.maximize.length === 0 // GNOME 49+ dropped the param
+                ? null
+                : Meta.MaximizeFlags.BOTH;
+            GLib.idle_add(GLib.PRIORITY_DEFAULT_IDLE, () => {
+                try {
+                    window.assertExistence();  // window may have been closed
+                } catch {
+                    return GLib.SOURCE_REMOVE;
+                }
+                maximizeFlags === null
+                    ? window.maximize()
+                    : window.maximize(maximizeFlags);
+                return GLib.SOURCE_REMOVE;
+            });
             return;
         }
```

`GLib` and `Meta` are already imported at the top of `tilingWindowManager.js`.

## Environment

- GNOME Shell 50.1 / mutter 50.1 (Wayland)
- Extension: `tiling-assistant@ubuntu.com` version 54, code on `main` is identical at the affected lines
- Crash observed during edge-tiling a window to maximize across a monitor change

Note: `_prepareAnimationInfo` in gnome-shell itself (`windowManager.js:1281`) could also be hardened against a detached actor (guard `actor.paint_to_content`), but the extension is where the synchronous `move_to_monitor` → `maximize` sequence originates, so the fix above is the more direct one. Happy to open a PR if this direction looks right.
