### ISSUE TITLE
Always on top setting lost when tiling window

### ISSUE THREAD

**Issue by loubilk** [Leleat/Tiling-Assistant#343]
**Describe the bug**
Always on top setting lost when tiling window

**Steps To Reproduce**
Enable Always on Top in any window
Move to any side of the screen to tile the window
Check Always on Top setting in the window, it's disabled now

**System Info:**
 - Distro (incl. version):  Debian GNU/Linux 12 (bookworm) x86_64
 - GNOME Shell version: GNOME 43.9
 - Extension version and from where (e. g. EGO, `main` branch...): EGO
 - XOrg/Wayland: XOrg

**Journalctl logs**

Error in size change accounting.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x558f3048fc30] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x558f2e790fd0] is on because it needs an allocation.
Error in size change accounting.

**Comment by Leleat** [comment]
That is actually intentional. The idea behind is that: if you tile a window it, it shouldn't overlap other windows (within the tile group). So unsetting the Always-on-top shouldn't really matter. In fact, it allows the feature like having multiple windows [share the same tile within a tile group](https://github.com/Leleat/Tiling-Assistant/wiki/Window-Grab-Modes#adaptive-tiling)... and it would be weird to have a tiled window visible but not the rest of the tile group.

So what is your workflow like that you'd want keep always-on-top enabled after a window is tiled? Based on this issue, I guess, you also disabled the `Tile Groups` feature, right?

**Comment by loubilk** [comment]
Thanks for your quick response and effort to maintain this great extension!.
I understand is intentional and make sense, my workflow is a bit different since I have an app using all my monitors running all the time on the background, so it would be nice to have the option to disable this.. 
Do you know any workaround to do this? 

Thanks in advance

**Comment by Leleat** [comment]
>  Do you know any workaround to do this?

You need to comment out the line 151 in the file `~/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/tilingWindowManager.js` (i. e. put `//` at the start of the line). The line should  then look like this

```
// window.unmake_above();
```

After making that change, log out and back in.

**Comment by loubilk** [comment]
Thank you so much, with that change is working now for my particular workflow!
