### ISSUE TITLE
Create a settings toggle to disable the `Single click on titlebar toggles maximization` behavior

### ISSUE THREAD

**Issue by kebb549575** [Leleat/Tiling-Assistant#355]
[Taken from AskUbuntu](https://askubuntu.com/questions/1512606/how-to-disable-ubuntu-24-04s-toggle-maximize-on-titlebar-single-click) (it's not me) but others and I completely agree:

> I'm used to having to double click to toggle a window's maximization. Right now, if I single click on a window, it toggles its maximization (although only when the window is already maximized). I'll have an app open and it's maximized, then I click once on the titlebar and it becomes smaller. I don't want that, I only want that when I double click, and I can't find the corresponding dconf setting. Can anyone help? ...It's very annoying.

**Briefly describe how the feature should work**

Please create a toggle to disable the `Single click on titlebar toggles maximization` behavior.

**Explain why this feature should be added**

[In the AskUbuntu](https://askubuntu.com/questions/1512606/how-to-disable-ubuntu-24-04s-toggle-maximize-on-titlebar-single-click) post people simply recommend disabling the Ubuntu Tiling Assistant. I want to use the tiling assistant and only want to disable this one `Single click on titlebar toggles maximization` feature.

**Comment by Leleat** [comment]
"Single click to maximize" isn't a feature, [it's a bug](https://github.com/Leleat/Tiling-Assistant/issues/327). It's already fixed in the latest version of Tiling Assistant but it didn't make it into Ubuntu yet. I don't know how Ubuntu's extension update process works. I guess you'll get the fix with the next point release... but this is just a guess, I don't know.
