### ISSUE TITLE
media & schemas missing from tiling-assistant@ubuntu.com

### ISSUE THREAD

**Issue by TheNullicorn** [Leleat/Tiling-Assistant#359]
**Describe the bug**
The extension that comes bundled with Ubuntu 24.04 is missing the `media` and `schemas` directories in `/usr/share/gnome-shell/extensions/tiling-assistant@ubuntu.com/`. It looks like the same situation and symptoms as #218, ie invisible panel indicator.

Apologies if this is a downstream issue. I couldn't find a repo for the '@ubuntu.com' package of this if there is one.

**Steps To Reproduce**
I haven't personally touched the extension's directory, so I believe it came installed this way. It was a fresh installation of Ubuntu 24.04 LTS with the 'Default selection' of applications.

**System Info:**
 - Distro: Ubuntu 24.04 LTS
 - GNOME Shell version: 46
 - Extension: `tiling-assistant@ubuntu.com` version 46; pre-installed by OS
 - XOrg/Wayland: Wayland

**Comment by Leleat** [comment]
> Apologies if this is a downstream issue. I couldn't find a repo for the '@ubuntu.com' package of this if there is one.

Indeed, this is a downstream issue. It looks like it was reported here https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-tiling-assistant/+bug/2040167. It looks like the panel indicator not showing is because the `media/` isn't included in the extension.

That said, I don't know if the exclusion of `media/` was intentional or not. The panel indicator is hidden behind the 'Advanced/Experimental' setting and I don't know if Ubuntu 'supports' the advanced/experimental settings.

Either way, there isn't any thing I can do here, so I am closing this. Your best bet is to ask/report it to ubuntu (on their website/issue tracker).
