### ISSUE TITLE
Resizing two tiled windows does not work if a non-tiled window hovers the unfocused one

### ISSUE THREAD

**Issue by julienfalque** [Leleat/Tiling-Assistant#368]
**Describe the bug**

When you have two windows tiled together and want to resize both (i.e. using their common edge), if there is a third, non-tiled window that hovers the unfocused tiled window, then only the focused window actually gets resized, breaking the tiling group.

**Steps to Reproduce**

1. Tile a window in top right corner of the screen
2. Tile another one in the bottom right corner. Both should be grouped so that, if you resize them using the common edge, both are resized as expected
3. Put a third window over one of the tiled windows, even a few pixels are enough
4. Focus the other tiled window
5. Try to resize tiled windows using the common edge

**System Info:**

 - Ubuntu 24.04
 - GNOME Shell 46
 - Extension version 46 (bundled)
 - Wayland

**Comment by Leleat** [comment]
That's intentional.

You probably disabled the setting `Raise Together` (under General > Tile Groups). This "loosens" the concept of tile groups and only non-overlapping tiled windows will be considered. Otherwise you may end up with unexpected situations. For instance,

1. if you've tiled 2 windows side by side
2. Focus a maximied window
3. focus 1 of the tiled windows and resize it

I think it would be pretty unexpected if the non-visible tiled window would resize along with it.

**Comment by julienfalque** [comment]
Ah yes, enabling the *Raise together* setting improves this, thanks 👍
