### ISSUE TITLE
Where can I find the layouts file? (Extension update from v14 to v15 or later)

### ISSUE THREAD

**Issue by ibLeDy** [Leleat/Tiling-Assistant#64]
I would like to know where are the configs stored, as before I could backup `.TilingAssistantExtension.layouts.json`, and since the extension got updated, seems to not use that file anymore, and I can't find the new one.

**Comment by Leleat** [comment]
I moved the new layouts file to the extensions folder, so that the files gets removed, if someone deletes the extension. I've also renamed the file to just `.layouts.json` because I've added a `layout search` mode via keybinding so that people don't have to remember the layouts keybinding (and reworked the system to be dynamic in number and no longer hardcoded).

So you can't just move and rename the file. The old layouts are now 'objects' and with the old array as the `rect` property and a new name property (which can be optionally empty). So you need to manually edit `.TilingAssistantExtension.layouts.json` and rename it to `.layouts.json` or add them via the GUI. 

Example conversion of a layout:

> [[{"x":0,"y":0,"width":0.5,"height":0.5}]]

to

> [**{"name":"","rects":**[{"x":0,"y":0,"width":0.5,"height":0.5}]**}**]

**Comment by ibLeDy** [comment]
Okay, I already re-added the layouts before creating the issue, so I will just backup the `.layouts.json` from the extension folder then.

**Comment by Leleat** [comment]
> Okay, I already re-added the layouts before creating the issue, so I will just backup the .layouts.json from the extension folder then.

Alright, I'll leave this open for a few weeks in case there are more people who used layouts before and are wondering what happened... 

<sub>Sorry, didn't think about compability here (^^')</sub>

**Comment by Leleat** [comment]
Per #68 I moved the layouts file to `$XDG_CONFIG_HOME/tiling-assistant/layouts.json`. This time I added compability code so you don't have to recreate the layouts though.

You need to click the *Save*  button in the `Layouts` tab once for the file to be created at the new location otherwise only the old file at `~/.local/share/gnome-shell/extensions/.layouts.json` will be loaded...
