### ISSUE TITLE
Add translations

### ISSUE THREAD

**Issue by eldelacajita** [Leleat/Tiling-Assistant#72]
Just adding this issue so anyone interested in helping with translations can be notified if/when they are implemented. No pressure!

**Comment by eldelacajita** [comment]
I can help with Spanish translation.

**Comment by Leleat** [comment]
@eldelacajita I've setup the translations. Just open a PR with the translated ` /tiling-assistant@leleat-on-github/po/es.po` file.

In case you are unfamiliar with it:
`msgid` is the to-be translated text and the translated text goes into the `""` of `msgstr`. You can use any text editor to edit the `es.po` file but the text may be hard to read. There are 'specialized' apps to handle `po` files. For example, I use `Poedit`, which is very simple to use.

Feel free not to translate everything since it is quite a bit text after all. Also the `Changelog` stuff might not be worth it since I am constantly adding to it...

**Comment by Etamuk** [comment]
Thanks for that. I will work on German translation :-)

**Comment by Leleat** [comment]
> Thanks for that. I will work on German translation :-)

Thanks you! Should I create a `de.po` for you?

PS. Ich habe mich bereits an einer deutschen Übersetzung versucht, aber dann aufgegeben. Habe bemerkt, dass ich keine Ahnung habe, wie die ganzen Begriffe (wie z. B. 'Tiling') im Deutschen lauten xD

**Comment by Etamuk** [comment]
> 
> Thank you! Should I create a `de.po` for you?
> 
Thanks, but I can do that also. I have not finished the translation. I had to find out that I only used the "basic" tiling feature. Simply DND, ready :-) 
So I have to learn and understand the other functions.
> PS. Ich habe mich bereits an einer deutschen Übersetzung versucht, aber dann aufgegeben. Habe bemerkt, dass ich keine Ahnung habe, wie die ganzen Begriffe (wie z. B. 'Tiling') im Deutschen lauten xD

Dein Deutsch klingt aber sehr gut, soweit ich das von diesem Zweizeiler erkennen kann :-) Tiling wäre einfach "Kacheln". Beispielsweise der Browser Vivaldi verwendet für diese Funktion ja auch den Begriff "Kachel". 
Viel schlimmer ist dabei aber das Verstehen der Funktionen. 
But I will ask when I need some help with it :-D

**Comment by eldelacajita** [comment]
> @eldelacajita I've setup the translations. Just open a PR with the translated ` /tiling-assistant@leleat-on-github/po/es.po` file.

Thanks for that! I'll have a look and see what I can do. I'm still finding my way around git, but I think I'll manage.

**Comment by Leleat** [comment]
Closing this issue as it's not a 'bug' and not really a 'specific feature', which can be implemented with _one_ pr, but a continuuous process of additions.

If you have questions, feel free to comment here. Otherwise just direclty open a PR.

**Comment by Leleat** [comment]
In case you are still working on the translations. I've dropped the `User Guide` and `Changelog` tab from the settings making the `main.pot` significantly shorter, since most people probably didn't read them anyway. I've updated the `main.pot` and `es.po` file. Sorry, for the trouble, if you started translating them.

**Comment by eldelacajita** [comment]
Thanks for the heads up! 

I just started translating it... and boy is this harder than I thought. Same fundamental problem as in German: we don't even have a word for "tiling". I'll research a bit how other projects solved it.
