### ISSUE TITLE
Checkout my experiment with always-on-top floating windows

### ISSUE THREAD

**Issue by nobodypb** [Leleat/Tiling-Assistant#75]
Hi @Leleat fist of all I have to state, that I pretty much love your extension. It's able to provide me a similar and in some cases even better experience than FancyZones on Windows, which I also love. 
However, since I heavily rely on my mouse, I've found some sharp edges and thought of ways to round them a little bit.
I've experimented with inverting the current ctrl behaviour and making floating windows stay always on top, but getting transparent if covering anything. 
I would by happy if you could checkout my code and give me feedback what you think about that behaviour and if that possibly could be integrated into your extension: https://github.com/nobodypb/Tiling-Assistant/tree/untiled-always-on-top

Though this was the first time I've fiddled with the gnome-shell so please forgive me, if I broke with conventions or smth.

**Comment by Leleat** [comment]
> https://github.com/nobodypb/Tiling-Assistant/tree/untiled-always-on-top

Thanks, I'll take a look.

> Though this was the first time I've fiddled with the gnome-shell so please forgive me, if I broke with conventions or smth.

Don't worry, I am not a developer and just picking up programming/JS along my journey of creating this extension. So I don't know or barely have any standards ;)

> FancyZones on Windows

I've only heard of (and watched a video on yt about it now). I like the feature of pre-defining layouts and than `Shift`-dragging a window around. Although I don't know how well it would work with this extension since I don't really have fixed layouts. How does FancyZones handle it, if for example the user defined a 3 column layout, which spans the entire screen, and there are 2 rows of tiled windows. Would it try to adapt the 3 column layout to the existing 2 tiled windows, would it force the 2 rows to be 2 columns or would it just ignore 2 tiled windows and start a new layout on top of them...?

PS. Your first commit (d7e3cad6f03781463a027eaa98db7691670232eb) says it catches an error. Can you tell me the STR so that `window.tileGroup` is `falsy`?  That's definitely a bug and in theory shouldn't happen and I'll need to fix it. I check at the beginning of the function that `window.isTiled`, which means that there should be always a `tileGroup` (array) of at least 1 window (the tiled window itself).

**Comment by Leleat** [comment]
Alright, did try it out a bit and here my opnion.

- invert ctrl-drag:
    - makes sense; I like it. It would basically be a mouse-based tiling mode with floating windows being the exception
    - it complements the keyboard-driven `Semi Tiling Mode` well; so I guess it makes sense to put them into a separate settings tab together?
    - I think the current behaviour needs to be changed then because if there are no (tiled) windows, nothing happens. I guess in that case the work area (maximized windows) should be split up. What do you think?

- untiled windows stay on top:
    - not sure about this one (especially the transparency can be very messy/distracting; see screenshot); what is your reasoning behind? Looks like it's would be mainly for utility windows (like calculator), right?

![Screenshot from 2021-05-22 14-29-58](https://user-images.githubusercontent.com/53054301/119230094-4795d180-bb0a-11eb-9771-e402cde0b5a2.png)

- untile covered window:
    - also unsure about this one. What's your reasoning behind it?
    - it's a feature that a window may be part of multiple tileGroups so it would be raised at different occasions. Since this feature optional though, that's not really a big problem.
    - However if a window is untiled, it may be in a higher stack position than other tiled windows, potentionally prompting the Tiling Popup to appear and messing up TileGroups. For example here:

![output](https://user-images.githubusercontent.com/53054301/119230606-89c01280-bb0c-11eb-8bbf-e6467f8af0cc.gif)

**Comment by nobodypb** [comment]
Thank you for your extensive feedback!

About FancyZones: Like I said, some things about your extensions I like more than how FancyZones handle it. FancyZones is more like permanently splitting your screen in predefined and fixed areas, which you can't resize on-the-fly. It's so far the best I found for Windows, but I really miss the resizing and splitting features of Tiling Assistant. There also can only be one layout active for a workspace at a time, which I consider good, because it simply forces me to use more workspaces, if one is filled and is very simple to understand and keep an overview of.

About my "Catch error" commit, I can't say anything, because I only found it in the log and decided to catch it. It said `window.tileGroup` was `undefined`. I also thought, that there must be a underlying cause, but wanted to have a detailed look later on. 
Thought there are various bugs that arose, once I used always-on-top windows, so that might be connected.

Before I move on, I want to tell you something about my usecase, because that will make my reasons clearer:
I recently bought a Samsung CRG9 ultrawidescreen with 32:9 aspect ratio. At that size of screen, maximized windows barely make any sense. So I want most of my windows to be tiled all the time, with only small exceptions, like dialogues or sometimes a calculator. I additionally make strong use of workspaces and don't like to have windows stacked on top of each other, it feels like a waste of time to search for a covered window, when I just could quickly move two workspaces further and have it right in front of me.
So the idea of my workflow is, to always have a single layer of tiled windows, which are only sometimes overlapped by utilities, or newly created windows, that yet have to be moved in place.
Btw. I don't use a tiling wm, because I like having the freedom to use floating windows if I decide to.

* **invert ctrl-drag**
  - This is an option I took over from FancyZones (though the key `shift` there) and which I use, since I always want to divide my screen.
  - How does the `Semi Tiling Mode` work? I never tried that.
  - In fact I tried what happens, if you allow the ctrl-drag on empty screens and found it to be too invasive, but it might be a good idea to allow enabling that via an option. On empty screens you always can press ctrl to tile the window using the edge behaviour thought.
  
* **untiled windows stay on top**
  - Well, I should have made the transparency configurable, that's something very opinionated.
  - As I only use few untiled auxiliary windows it totally makes sense to have them always on top. But I understand that this differs in other workflows. 
  - I think this feature should only be activated if there are tiling groups on the current screen at all and maybe also disabled for maximized windows, to prevent such messy screens.
  - It might also be a good idea to have a configurable black or whitelist to define which apps should have this behaviour at all.
  
* **untile covered window**
  - The reason is, that I like to always have only one layer of windows on a single workspace. I simply don't like to have windows hidden somewhere, that I need to search for. I'd move them to another workspace instead.
  - So when a window would get covered up, I pop it out to move it somewhere else instead.
  - While having the "raise together" option enabled, I haven't found out how to use it, yet. It might also just not work on my setup for some reason
  - I haven't discovered the last point, since I used this feature together with my "always-on-top" feature I guess. But there for sure is a method to prevent this, possibly by just focusing the untiled window?

Btw. if you didn't recognized I also enabled ctrl-grab tiling of windows dragged fram a diffrent monitor.

**Comment by Leleat** [comment]
> How does the Semi Tiling Mode work? I never tried that.

It basically allows you to open apps in a tiled state. That way you don't have to open a window and then tile it. It's fully optional, meaning the user has to actively use it. [Here](https://github.com/Leleat/Tiling-Assistant/blob/master/Guide.md#Semi-Tiling-Mode) is an explanation of the feature.

> In fact I tried what happens, if you allow the ctrl-drag on empty screens and found it to be too invasive, but it might be a good idea to allow enabling that via an option. On empty screens you always can press ctrl to tile the window using the edge behaviour thought.

Fair point. Did you also try to always enable the screen edges for tiling as well with the ctrl-drag inverted so that there is at least a way to tile on an empty/non-tiled workspace without having to hold `Ctrl`?

> Well, I should have made the transparency configurable, that's something very opinionated.

I'll have to think about the transparency. In its current state it would be a no from me (even if it's optional via a setting) because it's to specific to your already very specific workflow.

> It might also be a good idea to have a configurable black or whitelist to define which apps should have this behaviour at all.

A whitelist for always-on-top floating windows sounds good to me.

> So when a window would get covered up, I pop it out to move it somewhere else instead.

> While having the "raise together" option enabled, I haven't found out how to use it, yet. It might also just not work on my setup for some reason

It's a feature that you can cover up tiled windows. This way 1 window can be part of multiple tileGroups and be raised together at different occasions. The "raise together" is about having a tiled layer and a bunch of floating windows/layers. The problem here is that it doesn't suit your workflow because you don't have overlapping windows since your screen is so huge. Here an example with an explanation:

![output](https://user-images.githubusercontent.com/53054301/119261930-f8fb3c80-bbc8-11eb-9f9a-14cc22227673.gif)

There are 2 tileGroups here. 1: [`VSCode`, `GEdit`] and 2: [`VSCode`, `Firefox`]. You can see `SimpleScreenRecorder` overlapping `VSCode` and the window at the left. If I focus one window the other one will be raised and fully visible as well. `SimpleScreenRecorder` isn't overlapping the other window anymore. `VSCode` is part of 2 tileGroups here. So if I focus `GEdit`, `VSCode` will be raised. And if I focus `Fireox`, `VSCode` will be raised as well.

> **I haven't discovered the last point, since I used this feature together with my "always-on-top" feature I guess**. But there for sure is a method to prevent this, possibly by just focusing the untiled window?

Yeah, probably because of the always-on-top feature. Try it without it. Have 2 windows, which in their floating state overlap the future tiled states. Tile with keyboard shortcuts, so you don't change the original floating position. Now open a new window and tile it over the focused tiled window. The overlapped window will restore it's size and overlap the other tiled window and Tiling Assistant will detect free screen space and open the Tiling Popup. Here a gif:

![output](https://user-images.githubusercontent.com/53054301/119262929-7eccb700-bbcc-11eb-9ddf-c8c6e4e3e714.gif)


> I haven't discovered the last point, since I used this feature together with my "always-on-top" feature I guess. **But there for sure is a method to prevent this, possibly by just focusing the untiled window?**

Wouldn't automatically changing the focused window be weird for a user? 

> Btw. if you didn't recognized I also enabled ctrl-grab tiling of windows dragged fram a diffrent monitor.

Usually I only run a single monitor (21:9) setup. Can you please explain in more detail what that feature is?

**Comment by Leleat** [comment]
Closing due inactivity.

My stance on these propositions hasn't really changed. I'd merge a PR for some of the ideas, so please see my opinion above.
