### ISSUE TITLE
Pressing super+right then super+up should tile to top right corner

### ISSUE THREAD

**Issue by 2br-2b** [Leleat/Tiling-Assistant#87]
**Describe the bug**
If I press super+right then super+up, I expect the window to tile to the top-right corner. Instead, the window tiles to the right (expected) then to the top (unexpected)

**Steps To Reproduce**
Press super+right, then super+up

**Screenshots/-captures**
https://user-images.githubusercontent.com/43968991/127688690-761aa1a7-3ab0-449b-a5a5-805a1823d305.mov

**System Info:**
 - Distro (incl. version): Ubuntu 21.04
 - GNOME version: GNOME 3.38.4
 - Extensions version: 3.38.4
 - XOrg/Wayland: Wayland

**Journalctl logs**
Not applicable - this seems to be a behavioral issue, not a technical one.

**Additional context**
This could just be a behavioral issue, but it would be nice if this were an option.

Besides this, I love the extension! Thank you so much for developing it!

**Comment by Leleat** [comment]
I did experiment with this at some point (don't remember, if I published it on EGO though). In the end I removed it because the Tiling Popup (arguably this extension's main feature) interfered with it and popped up "unintentionally" more often than not.

But since I've added the option to disable the Tiling Popup now, I don't mind re-adding this feature.

**Comment by Leleat** [comment]
I remember this from other Distros (DEs) but can't find them atm. What's the expected behaviour for windows, which are at the corners and the keyboard shortcut towards one of the corner directions is pressed. For example, a window is in the top-right corner and the keyboard shortcut to tile to the right is pressed. Does the window get untiled or does it tile to the right half?

About the maximization state, is it also part of this "dynamic" tiling. Let's say the window is tiled to the top half. What do the shortcuts for tiling to the top and tiling to the bottom do?

**Comment by Leleat** [comment]
@2br-2b I've implemented it in `master` now (it doesn't move across monitors). Can you test it and see, if it's how you imagined it? It's the `Tiling State` of the `Dynamic Keybinding Behaviour` setting.

**Comment by 2br-2b** [comment]
I just tested this, and it works great! Thank you so much!

I'm not sure how it works over multiple monitors, but this works amazing right now!

My only other concern (which may be another issue - let me know if you want me to open another) is that the up and down keys don't seem to work the same as in Windows when the window is not tiled (though you can add other shortcuts for these):

https://user-images.githubusercontent.com/43968991/127905747-9d4fac3f-1b42-4375-8079-a8c86ecd8990.mp4

However, this last change has already made the extension so much easier for me to use! Thank you so much!

**Comment by Leleat** [comment]
> Super-up works perfect when "Tile to top" **and** "Toggle Maximization"

Well, only one of the shortcuts should be set to `Super`+`Up` :)

> super+down does not function the same...

Thanks for the explanation, I'll implement for the next extension version as a new option and name it 'windows-like' or something.

**Comment by Leleat** [comment]
> The functions it should do are:

What happens, if the window is maximized and `Super` + `Up` is pressed?

**Comment by 2br-2b** [comment]
> Well, only one of the shortcuts should be set to `Super`+`Up` :)

Well, when I set both, it works just like Windows does. Whether that's a bug or not, it's the way I've gotten this to work :-)

The master branch works great! The only differences I see from Windows are:
- When the window is on the right side of the screen and super+right is pressed, the window is moved to being tiled on the left side of the screen
- When the window is in the top-right or bottom-right corner and super+right is pressed, the window is tiled in the top-left or bottom-left
- When the window is in the top-right or bottom-right corner and super+left is pressed, the window is tiled in the top-left or bottom-left

But then, when I was testing this, I had the window on the left side of the screen and pressed super+right and the window was moved to the right side of the screen. I didn't even notice until reviewing the attached video. I will have to test to determine why this happened.

Honestly, after playing with this for a bit, I kinda like it how it is. The changes would be helpful for parity with Windows for new users, but it honestly works fine as-is.


https://user-images.githubusercontent.com/43968991/127938373-75994dbb-9cdb-4260-b9d3-0c2984856e85.mp4


The only other discrepancy I noticed is that, in Windows, when you press super+down to minimize a window then you press super+up, it unminimizes the page. This is shown at around 20 seconds in the last video. If it's in a bottom corner, it is restored to the same corner.

It probably waits until a different key is pressed or the mouse clicks somewhere to reset the super+up key. It'd take a bit more technical work behind the scenes to add this feature to Tiling Assistant (remembering which window was minimized and where it was tiled last.

Thank you so much for implementing this! These are just small, not-too-necessary improvements and the extension works amazingly! I already rated 5/5 on the Extensions store. Great work, and thank you so much for this wonderful extension!

**Comment by Leleat** [comment]
> Well, when I set both, it works just like Windows does. Whether that's a bug or not, it's the way I've gotten this to work :-)

Did you try it with just one of those 2 shortcuts set to `Super` + `Up`? That should be enough. If you have multiple keyboard shortcuts set to the same key combo, it will be 'random' which shortcut gets activated when pressing the key combo... If it didn't work with just either `Tile to top` **or** `Toggle Maximization` , did you maybe not unset GNOME's native `Super` + `Up`. That may have been such a case of GNOME's `Super` + `Up` being triggered instead of my extension's `Super` + `Up`.

> [...] I kinda like it how it is. The changes would be helpful for parity with Windows for new users, but it honestly works fine as-is.

Well, I am gonna leave it as is then  since I am lazy

> The only other discrepancy I noticed is that, in Windows, when you press super+down to minimize a window then you press super+up, it unminimizes the page  [...]
>
> It probably waits until a different key is pressed or the mouse clicks somewhere to reset the super+up key. It'd take a bit more technical work behind the scenes to add this feature to Tiling Assistant (remembering which window was minimized and where it was tiled last.

I'd say in 90% of the cases, if someone minimized a window, they'd go to a different window, which makes `Super` + `Up` no longer work with the minimized window... so it's probably not worth implementing this (again, lazy me :))

> Great work, and thank you so much for this wonderful extension!

Thanks for the feedback and this suggestion!

**Comment by 2br-2b** [comment]
> Did you try it with just one of those 2 shortcuts set to `Super` + `Up`? That should be enough. If you have multiple keyboard shortcuts set to the same key combo, it will be 'random' which shortcut gets activated when pressing the key combo... If it didn't work with just either `Tile to top` **or** `Toggle Maximization` , did you maybe not unset GNOME's native `Super` + `Up`. That may have been such a case of GNOME's `Super` + `Up` being triggered instead of my extension's `Super` + `Up`.

This is what I have for my keybindings in your app:
![image](https://user-images.githubusercontent.com/43968991/128258132-6bc03dbd-eb0f-432f-8d0f-60c4cd050d71.png)

And this is my keybindings in the settings app:
![image](https://user-images.githubusercontent.com/43968991/128258289-0677ea96-11a2-4218-badc-c05a029a7667.png)

This setup works flawlessly for me, so there's no issue there.

I may look into implementing one or two of the other features if I have time between the 100 other projects on my todo list and if I can understand the cryptographic text known as "javascript". Other than that, excellent work, and thank you so much for making this!

**Comment by fischer-felix** [comment]
Hi, it seems this does not work any more, when I replicate the exact setup as in the screenshot on gnome 46 and press Super + Right + Up, it just first tiles to the right and then to the top.

https://github.com/Leleat/Tiling-Assistant/assets/65448408/839f9937-5457-41b5-a902-4d0096a3887a

**Comment by Leleat** [comment]
@fischer-felix I don't have an issue. Did you check the "Dynamic Keybinding Behavior"?

**Comment by fischer-felix** [comment]
Indeed, I did not have that checked, thanks!
