### ISSUE TITLE
Disabling the keybinding for Tile Editing | Layout Selector

### ISSUE THREAD

**Issue by RobertlGy** [Leleat/Tiling-Assistant#91]
**Describe the bug**

I am not a professional person and I don't know how this Tile editing or layout selector works. Every time I use a pop us shows which tells cannot enter tiling mode and I just want to disable the tiling mode keybinding and some others as well
![image](https://user-images.githubusercontent.com/74289126/129432266-ac240b4a-1603-41d2-ad4b-c7abd666a8c3.png)

**Steps To Reproduce**

**Screenshots/-captures**

![image](https://user-images.githubusercontent.com/74289126/129432294-926d2f06-bc22-46eb-abeb-45af1c47750f.png)

**System Info:**
 - Distro (incl. version): Fedora
 - GNOME version: 40 

 - Extensions version: 23
 - XOrg/Wayland: XORG

**Journalctl logs**

**Additional context**

**Comment by Leleat** [comment]
You disable a keyboard shortcut by double-clicking on the shortcut. Then it waits for your input. You then press `Backspace`. (That's also the way to do it in GNOME).

FTR; the `Layout selector` only works, if you created a layout in the `Layouts` setting tab. `Tile Editing Mode` requires at least 1 tiled window on the display. That mode is there so that you can manage your tiled windows with your keyboard (resize, close, untile...). [Here](https://github.com/Leleat/Tiling-Assistant/blob/master/GUIDE.md#Tile-Editing-Mode) is a guide for it.
