### ISSUE TITLE
Add support for ultrawide monitors (3 column layout)

### ISSUE THREAD

**Issue by urbenlegend** [Leleat/Tiling-Assistant#94]
The default 2x2 grid is sometimes too big for ultrawides. Can we get an easy to use 3x2 snap grid as well? In Windows 11, it is really easy to divide the screen into 3 by simply dragging a window to the top edge and then sliding along it until the tile preview changes to 1/3.

Currently the workaround is to snap two windows side by side and then Ctrl drag a window in between them. This works but is slow and cumbersome and also requires snapping 3 windows instead of just one or two.

**Comment by Leleat** [comment]
Sorry, I'm not really interested in it. 

But I am open for a PR, if someone else wants to implement it. It probably should be a separate "mode" (like ctrl-dragging), since it would conflict with the "adaptiveness" of the current tiling previews.

**Comment by urbenlegend** [comment]
I might be interested in making a PR for this actually. I've been diving heavily into Javascript recently, but I don't have any experience with making Gnome extensions yet. I am down to pick it up though.

The ctrl-drag mode seems to want to divide regions by two. Going along with your idea of creating a separate mode, I was thinking of perhaps using another keybind like Alt-drag which will divide regions by 3.

1.) Alt-drag with no windows snapped will show 1/3 regions: left, center, right. Dragging along top and bottom edges will split the region in half (1/6 of screen area).
2.) Alt-drag over an empty region next to a snapped window will divide that region up into smaller 1/3 regions with the same behavior as in (1).
3.) Alt-drag over a snapped window will only show left 1/3 and right 1/3. You can't split a window in two obviously.
4.) Not sure if alt-drag over a window edge makes sense, so I'll leave that as a no-op for now.

What do you think?

Since you know the code best, where's the best place for me to get started making these modifications. It will help to get a starting off point where I can begin understanding the code.

**Comment by Leleat** [comment]
> I might be interested in making a PR for this actually. I've been diving heavily into Javascript recently, but I don't have any experience with making Gnome extensions yet. I am down to pick it up though.

Thanks, sounds good.

>  ctrl-drag mode seems to want to divide regions by two. Going along with your idea of creating a separate mode, I was thinking of perhaps using another keybind like Alt-drag which will divide regions by 3.

I haven't used a W11 preview before; only seen videos about it. But my initial thought was a completely new mode using a fixed but predefined layout. For example, the user defines a 3 column layout. Then they can alt-drag a window to one of those fixed columns. I don't mind your approach either. Up to you.

> Since you know the code best, where's the best place for me to get started making these modifications. It will help to get a starting off point where I can begin understanding the code.

`extension.js` and `prefs.js` (and optionally, `stylesheet.css`) are mandated by gnome shell's extension system. 

`prefs.js` is about the extension's settings page (the `prefs.ui` files are xmls and give you the actual settings page. It can be opened with the app "Glade". However `prefs40.ui` needs to be edited manually, since Glade doesn't support GTK4 and isn't maintained anymore, I think). `schemas/org.gnome.shell.extensions.tiling-assistant.gschema.xml` defines the settings keys and need to be compiled, if the file changes. Not so interesting for you, if you don't intend to do anything about settings.

`extension.js` has to have 3 functions. `init`, `enable` and `disable`. These functions are called automatically at the proper time. When my extension is enabled, I basically just  delegate the functionality to the different (classes in the different) files. 1 file = 1 feature.

So for you the file of interest is `tilingMoveHandler.js` (and possibly `tilingUtil.js` as a general collection of functions). Note that `tilingMoveHandler.js` currently only exists in `master`. The version on EGO is slightly outdated and has a `tilingGrabHandler`, which also contains resizing code for tileGroups. But on `master` I decided to split it up (and do some other minor changes).

The tilingMoveHandler gets construct'ed on `extension.js`'s enable() call and destroy'ed on the disable() call. The `_onMoveStarted`, `_onMoving` and `_onMoveFinished` functions get called via window signals.

Here are extension guides:
https://gjs.guide/extensions/

And here some docs:
https://gjs-docs.gnome.org/
You need to enable the different modules(?). Most interesting for you are probbly `Meta` (here is the api for windows and rectangles), maybe `Clutter` and `St` as well.

Good luck, if you have any questions, feel free to ask them 😄

PS. I am not a developer, so don't think too depply about why I did stuff the way I did... I probably just didn't know better. So feel free to suggest improvements, if you come up with some 😃

**Comment by urbenlegend** [comment]
Wow, thanks so much for the detailed info! That's a great starting point for me. I'll get started on this when I have the time.

**Comment by Leleat** [comment]
> Wow, thanks so much for the detailed info! That's a great starting point for me. I'll get started on this when I have the time.

Are you still planning on working on this? If not, I plan to do it myself for the next release. If you do want to work on it, don't worry about not making it for the next release. I just want to know, so there is no duplicated effort.

PS. I did a bit of reorganizing / refactoring. The relevant files for you would be at `moveHandler.js` (and possibly `geometry` and `utility.js`) at `tiling-assistant@leleat-on-github`.

**Comment by Leleat** [comment]
Closing this as the new extension version is on EGO now.
